name: 'Android Github Action'
description: 'Android Github Action that build Android project, set up JDK 1.8, run unit tests and build debug APK.'
author: 'Vukan-Markovic <vukan.markovic97@gmail.com>'
branding:
  icon: 'box'
  color: 'green'
runs:
  using: 'docker'
  image: 'Dockerfile'
